### PR TITLE
Debug Dad

### PR DESCRIPTION
**Pull request by braxtonhall**
@SmallBeanMachine review me

### CODE REVIEW

**Comment by SmallBeanMachine** [comment]
actually, which do you think would be funnier? i see both versions working

**Comment by braxtonhall** [comment]
OK I see that being pretty funny. The question is, where should it stop? At a special character? I would want to include dashes, but exclude things like parens, brackets, commas, semis etc

**Comment by braxtonhall** [comment]
OK
`(i'm foo) bar` should be `foo`
`i'm (foo) bar` should be `(foo) bar`

We're going to need a good regex

**Comment by SmallBeanMachine** [comment]
hmm yeah this is going to be one weird regex

ill write some tests / think of something in the morning

**Comment by SmallBeanMachine** [comment]
okay, i think before we start anything it's best to explain how the bot should work in english somewhat rigorously:

looks for the first occurrence of `i'm/im/i am`
after this, it will match every character until it encounters one of:` .,;`

then there's two special cases: parentheses/brackets and dashes
if the search started in a pair of parentheses/brackets, then it must end before the parenthesis/bracket that closes it
same goes for a dash - though dashes cant be nested like parentheses can, so it should be easier to check

some additional tests i came up with:
`i'm foo` should be `foo`
`i'm foo bar` should be `foo bar`
`foo - i'm bar - baz` should be `baz`
`i'm bar - foo` should be `bar`
`(i'm (foo) bar)` should be `(foo) bar`
`i'm foo. bar` should be `foo` (this test should behave the same way for all of `.,;`

**Comment by SmallBeanMachine** [comment]
after trying to write a regex to match balanced parentheses, im thinking it'd be cleaner / more maintainable if we didn't do this in regex. or at least not all of it. maybe we can have a regex that captures "too much", and then have a function that truncates the capture to the actual name.

**Comment by braxtonhall** [comment]
Aight @SmallBeanMachine I restored the old behaviour. Do you want to contribute on `braxtonhall:test` or merge this first and work on your own fork?

**Comment by SmallBeanMachine** [comment]
thanks! ill just work on this fork to keep everything in one place

**Pull request closed without merging**
