### PR TITLE
disable dad bot

### PR DESCRIPTION
**Pull request by SmallBeanMachine**

### CODE REVIEW

**Comment by braxtonhall** [comment]
LMAO I missed this.

**Review by braxtonhall — CHANGES_REQUESTED** [review]
NO! Instead, make it randomly send. Like 1/200 or smth
if (Math.random() < 0.005)

**Comment by braxtonhall** [comment]
nvm. i see you are no longer in the discord and probably don't want to work on this anymore 👀

**Comment by SmallBeanMachine** [comment]
Haha don't worry about it. Maybe if yall have a serious/nonserious channel this semester you can tailor the probabilities so that its more likely to make the joke in the nonserious channels? No clue :p

**Comment by SmallBeanMachine** [comment]
On another note I realize I never got the chance to say this: You guys were some amazing TAs. Really made the course tons better. Good luck with next sem, if you're TAing it again! :)

**Pull request merged**
